### ISSUE TITLE
Adding Metadata Embed and MB4 Conversion Tools

### ISSUE THREAD

**Issue by anakinsleftleg** [mikiher/audiobookshelf-windows#10]
I know the readme says that tone will eventually be replaced, but I'm wondering if there is any kind of time table on that? I'd prefer to run the Windows version of ABS but the Docker version is the only one that has all those extra tools which I'd like to use to manage my files as i get my library started. I can also use tools like inAudible which is very fast for converting mp3 to mb4 (faster than tone in ABS it seems) but the rest of the ux/ui isn't as nice as ABS.

While i'm here, i might ask about audiobook splitting too, perhaps these kinds of tools would really kick ABS up a notch, as great as it already is.

**Comment by mikiher** [comment]
Fixed with v2.11.0
