### ISSUE TITLE
Latest Release and previous flagged as viruses by Kaspersky

### ISSUE THREAD

**Issue by wtfmejt** [mikiher/audiobookshelf-windows#12]
<img width="668" alt="image" src="https://github.com/mikiher/audiobookshelf-windows/assets/1768232/750b39fe-e884-4edd-93ec-2fbae18ec4de">

**Comment by mikiher** [comment]
This is most probably a false positive. 
I'll check but I'm really not sure I can do anything about this at this point.

**Comment by wtfmejt** [comment]
When I first installed it a couple days ago it didn't get flagged. It just happened today.

**Comment by mikiher** [comment]
It's probably due to a recent update to the Kaspersky database. Again, this sometimes happens, plus this is an unsigned program, which makes antivirus programs more suspicious of it.

I'm planning to sign it at some point, after all audiobookshelf projects are moved under a new GitHub product umbrella (@advplyr is planning this).

**Comment by NovAProspekT-96** [comment]
Just had the same issue. Kaspersky immediately flagged it as "Trojan-Ransom.Win64.Nokoyama.bf" and removed it from my system.

**Comment by ShadoWrkr** [comment]
Same issue here. Kaspersky flags it immediately and deletes it. I really enjoyed ABS when I had it installed before. I'm hoping this can get resolved. I'm not keen on the idea of needing to disable my virus protection to use it.

**Comment by mikiher** [comment]
I found out you can report false positives to Kaspersky for further analysis, so I just did that. Hopefully this will be removed from their threats database.

**Comment by mikiher** [comment]
Got a **_very_** quick response from them:

>Sorry, it was a false detection. It will be fixed.
Thank you for your help.

**Comment by ShadoWrkr** [comment]
Fantastic. Thanks for following up!

**Comment by mikiher** [comment]
I'm closing this issue as resolved. Please re-open if you encounter this again
