### ISSUE TITLE
unable to use vpn to access library while off server network

### ISSUE THREAD

**Issue by RabidLime** [mikiher/audiobookshelf-windows#19]
trying to use NordVPN Meshnet to stream my library while at work using [these](https://meshnet.nordvpn.com/how-to/remote-files-media-access/audiobook-server#method-1-using-a-mobile-app) instructions, save for the Docker part, as i'm using you're awesome .exe

when trying to set up the Nord addresses, it says it can't connect. would this have anything to due with using your installer instead of Docker? chatted with NordVPN and they were stumped. just curious as this stuff is sort of out of my wheelhouse, i know just enough to be dangerous.

**Comment by mikiher** [comment]
I doubt this has anything to do with the Windows installer or the packing of Audiobookshelf within an .exe file.

I suggest seeking help on our [discord server](https://discord.gg/HQgCbd6E75) - there's excellent support offered there

**Comment by mikiher** [comment]
Closing this. If you still believe this is a Windows Installer/Exe issue, please re-open with more details.
