### ISSUE TITLE
Changing Port From Tray 

### ISSUE THREAD

**Issue by lemendoza956** [mikiher/audiobookshelf-windows#2]
When changing port From Tray and click save, it saves the directory in the box below instead of the port number. I have to change it on the config file.

**Comment by mikiher** [comment]
Ouch, sorry about that. This bug completely messes up the configuration. I will create a release with the fix soon.

I understand you were able to workaround by manually fixing the config file, but if problems still persist, just remove the tray app settings altogether from %localappdata%/AudiobookshelfTray
