### ISSUE TITLE
Server Crash - Large Podcast Add

### ISSUE THREAD

**Issue by shanespringer** [mikiher/audiobookshelf-windows#27]
Hello Team,

Guessing this is a low priority, but just reporting that adding a podcast with a large history (Stuff You Should Know) created a terminal crash that recovered after a service reboot.

The solution of increasing the memory buffer mentioned in [issue 2075 on docker](https://github.com/advplyr/audiobookshelf/issues/2075) seems pretty clearly related, but I'm not sure that there are similar steps in windows.

Logs are available on [Pastebin ](https://pastebin.com/f3cBg9fp)if they can be helpful.

**Comment by mikiher** [comment]
I'm going to close this issue as Won't fix. I'll try to reproduce this but the bug should be opened on the server, and its resolution should not just be "increase Node memory".

**Comment by mikiher** [comment]
OK, I've reproduced this and will open a server bug myself.
