### ISSUE TITLE
Change the update link to direct to the GitHub release page of the Windows repository.

### ISSUE THREAD

**Issue by TheTanka** [mikiher/audiobookshelf-windows#28]
I have noticed that the update link you can click on in the bottom left corner will direct you to the [original repository releases](https://github.com/advplyr/audiobookshelf/releases/tag/v2.16.2) instead of the [windows releases](https://github.com/mikiher/audiobookshelf-windows/releases/tag/v2.16.2) of this repository.

![2024-10-31_17-32](https://github.com/user-attachments/assets/e1e20671-fca1-4620-a9cb-8158e7afc6a1)

**Comment by mikiher** [comment]
Yes, this is the server releases page - it's there just for informational purposes.

Your Windows install will check for updates automatically whenever a new release goes out, or you can also check for updates manually by right clicking on the tray icon.
