### ISSUE TITLE
Error [AudioFileScanner] No such file or directory

### ISSUE THREAD

**Issue by Cobolt78** [mikiher/audiobookshelf-windows#5]
The bug I have found is long folder/file paths, I moved my audio books from my synology NAS to my windows machine for ABS, once I setup ABS and added the library I noticed some books were missing, upon looking through the logs I encounted Error [AudioFileScanner] No such file or directory. After looking at the file and folders that had the error they looked pretty long. As there were 70+ books to shorten I tried to enable longfilepaths in the registry to see if that fixed the problem but it didn't so I renamed the folder and files shorter and that solved the problem. 
It's not that big of an issue though.
Please find the attatched as an example of the problem faced (as I had already renamed all the problem books already to reproduce this error I just renamed the folder and file to be the longest windows would let me make it).

![ABS Error](https://github.com/mikiher/audiobookshelf-windows/assets/104347696/d864e0d1-b304-4c0b-838f-ff48d49823ab)
![Longpaths](https://github.com/mikiher/audiobookshelf-windows/assets/104347696/a3702fc3-e154-4e69-a986-0e3cb063d74e)
![Folderview](https://github.com/mikiher/audiobookshelf-windows/assets/104347696/9f051dbf-9070-4038-afd4-d214ef6dc3d4)

**Comment by mikiher** [comment]
This seems to be a server issue (although it's probably a windows-specific server issue) - I will look into this a bit more tomorrow.

**Comment by mikiher** [comment]
@advplyr, can you please transfer this issue to the server queue?

**Comment by advplyr** [comment]
Can't transfer it since you are the owner. It's fine we can reference this in the PR

**Comment by Cobolt78** [comment]
> OK, I was able to repro and understand your bug.
> 
> This is an issue with the ffprobe version that's installed by the server (and it is indeed a windows specific issue, since the server only attempts to find and install ffprobe on Windows installs). The ffmpeg binaries (including ffprobe) that are currently being downloaded by the server (from ffbinaries.com) are version 4.4.1, however it looks like windows long path support has only been added to ffprobe in version 5.1 (You did the right thing looking for LongPathsEnabled==1, but unfortunately it is not enough to have it enabled - applications also need to be modified to support long paths)
> 
> After switching to ffprobe 6.1, I successfully added a book with a long path.
> 
> [ffbinaries.com](https://ffbinaries.com/) only recently (on Dec 28 2023, to be precise) started to offer the latest versions of ffmpeg (5.1 and 6.1), but unfortunately have not yet updated their API to point 'latest' to 6.1. This means that I'll need to make a couple of code changes to hardcode downloading version 6.1, and also replace existing older versions that it installed.
> 
> Stay tuned...
> 
> In the meantime, if you want to manually fix this, you can:
> 
> * Download the latest (6.1) ffmpeg and ffprobe binaries from [here](https://ffbinaries.com/downloads)
> * Replace the ffmpeg.exe and ffprobe.exe files found in your config directory (by default it's at %localappdata%\Audiobookshelf\config`) with the binaries you downloaded.

Thanks alot for your help :) I will download the new 6.1 ffmpeg and ffprobe binaries and give it a go.

Thanks
